spring.application.name=jpademo

spring.datasource.url = jdbc:mysql://localhost:3306/demo_db
spring.datasource.username = root
spring.datasource.password = tanu3456
spring.jpa.properperties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto = update
